{{ $jnvArch := .chezmoi.arch }}
{{ if eq $jnvArch "arm64" }}{{ $jnvArch = "aarch64" }}{{ end }}
{{ if eq $jnvArch "amd64" }}{{ $jnvArch = "x86_64" }}{{ end }}

[".local/bin/jnv"]
    type = "archive-file"
    url = "https://github.com/ynqa/jnv/releases/download/v{{ template "get-github-latest-version" list "ynqa/jnv" }}/jnv-{{ $jnvArch }}-unknown-linux-gnu.tar.xz"
    path = "jnv-{{ $jnvArch }}-unknown-linux-gnu/jnv"
    executable = true
    refreshPeriod = "168h"

{{ $zoxideArch := .chezmoi.arch }}
{{ if eq $zoxideArch "arm64" }}{{ $zoxideArch = "aarch64" }}{{ end }}
{{ if eq $zoxideArch "amd64" }}{{ $zoxideArch = "x86_64" }}{{ end }}

[".local/bin/zoxide"]
    type = "archive-file"
    url = "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ template "get-github-latest-version" list "ajeetdsouza/zoxide" }}/zoxide-{{ template "get-github-latest-version" list "ajeetdsouza/zoxide" }}-{{ $zoxideArch }}-unknown-linux-musl.tar.gz"
    path = "zoxide"
    executable = true
    refreshPeriod = "168h"

{{ $deltaArch := .chezmoi.arch }}
{{ if eq $deltaArch "arm64" }}{{ $deltaArch = "aarch64" }}{{ end }}
{{ if eq $deltaArch "amd64" }}{{ $deltaArch = "x86_64" }}{{ end }}

[".local/bin/delta"]
    type = "archive-file"
    url = "https://github.com/dandavison/delta/releases/download/{{ template "get-github-latest-version" list "dandavison/delta" }}/delta-{{ template "get-github-latest-version" list "dandavison/delta" }}-{{ $deltaArch }}-unknown-linux-gnu.tar.gz"
    path = "delta-{{ template "get-github-latest-version" list "dandavison/delta" }}-{{ $deltaArch }}-unknown-linux-gnu/delta"
    executable = true
    refreshPeriod = "168h"

[".local/bin/jq"]
    type = "file"
    url = "https://github.com/jqlang/jq/releases/download/{{ template "get-github-latest-version" list "jqlang/jq" }}/jq-linux-{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h"

[".local/bin/argocd"]
    type = "file"
    url = "https://github.com/argoproj/argo-cd/releases/download/v{{ template "get-github-latest-version" list "argoproj/argo-cd" }}/argocd-linux-{{ .chezmoi.arch }}"
    executable = true
    refreshPeriod = "168h" 

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1

[".config/tmux/tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/gpakosz/.tmux/refs/heads/master/.tmux.conf"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".tmux/plugins/tmux-resurrect"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/nvim"]
    type = "archive"
    url = "https://github.com/llajas/kickstart.nvim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/nvim/lua/custom/plugins/lualine.lua"]
    type = "file"
    url = "https://raw.githubusercontent.com/xero/dotfiles/refs/heads/main/neovim/.config/nvim/lua/plugins/lualine.lua"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/nvim/pack/github/start/copilot.vim"]
    type = "archive"
    url = "https://github.com/github/copilot.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
