# roles/common_packages/tasks/main.yml
- name: Initialise pkg_list
  set_fact:
    pkg_list: []

- name: Assemble package list
  set_fact:
    pkg_list: >-
      {{
        pkg_list +
        [ item.get(ansible_facts.os_family) or item.get(ansible_facts.distribution) ]
      }}
  loop: "{{ development_tools | default([], true) }}"
  when: item is mapping and (item.get(ansible_facts.os_family) is defined or item.get(ansible_facts.distribution) is defined)

- name: Install packages
  ansible.builtin.package:
    name: "{{ pkg_list | unique }}"
    state: present
  when: pkg_list | length > 0          # skip task if nothing to install
