- name: Assemble package list
  set_fact:
    pkg_list: >-
      {{
        (pkg_list | default([])) +
        [
          item.get(ansible_facts.os_family)
          or item.get(ansible_facts.distribution)
          or item.name
        ]
      }}
  loop: "{{ packages }}"
  when: item is mapping

- name: Install packages
  ansible.builtin.package:
    name: "{{ pkg_list | unique }}"
    state: present